CREATE TABLE "mytable" (
  "-- Criação do banco de dados" text
);

INSERT INTO "mytable" ("-- Criação do banco de dados")
VALUES
('DROP DATABASE IF EXISTS hospital;'),
('CREATE DATABASE hospital;'),
('USE hospital;'),
('-- Tabela Convenio'),
('CREATE TABLE convenio ('),
('id_convenio INT PRIMARY KEY AUTO_INCREMENT'),
('nome VARCHAR(100)'),
('telefone VARCHAR(20)'),
('cobertura VARCHAR(200)'),
(');'),
('-- Tabela Paciente'),
('CREATE TABLE paciente ('),
('id_paciente INT PRIMARY KEY AUTO_INCREMENT'),
('nome VARCHAR(100) NOT NULL'),
('cpf CHAR(11) NOT NULL UNIQUE'),
('data_nascimento DATE'),
('telefone VARCHAR(20)'),
('endereco VARCHAR(200)'),
('id_convenio INT'),
('FOREIGN KEY (id_convenio) REFERENCES convenio(id_convenio)'),
(');'),
('-- Tabela Medico'),
('CREATE TABLE medico ('),
('id_medico INT PRIMARY KEY AUTO_INCREMENT'),
('nome VARCHAR(100) NOT NULL'),
('crm VARCHAR(20) NOT NULL UNIQUE'),
('especialidade VARCHAR(80)'),
('horario_atendimento VARCHAR(100)'),
(');'),
('-- Tabela Consulta'),
('CREATE TABLE consulta ('),
('id_consulta INT PRIMARY KEY AUTO_INCREMENT'),
('data_consulta DATE NOT NULL'),
('horario TIME'),
('diagnostico TEXT'),
('receita TEXT'),
('id_paciente INT NOT NULL'),
('id_medico INT NOT NULL'),
('FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente)'),
('FOREIGN KEY (id_medico) REFERENCES medico(id_medico)'),
(');'),
('-- Tabela Internacao'),
('CREATE TABLE internacao ('),
('id_internacao INT PRIMARY KEY AUTO_INCREMENT'),
('quarto VARCHAR(10)'),
('data_entrada DATE'),
('data_saida DATE'),
('id_paciente INT NOT NULL'),
('id_medico INT NOT NULL'),
('FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente)'),
('FOREIGN KEY (id_medico) REFERENCES medico(id_medico)'),
(');'),
('-- Tabela Exame'),
('CREATE TABLE exame ('),
('id_exame INT PRIMARY KEY AUTO_INCREMENT'),
('tipo_exame VARCHAR(100)'),
('data_exame DATE'),
('resultado TEXT'),
('id_paciente INT NOT NULL'),
('id_medico INT NOT NULL'),
('FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente)'),
('FOREIGN KEY (id_medico) REFERENCES medico(id_medico)'),
(');');
